BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.3
            Button:
                id: converter_btn
                text: 'Convert Miles to Kilometers'
                on_press: app.handle_convert()
            Button:
                id: converter_btn
                text: 'Convert Miles to Kilometers'
                on_press: app.handle_convert()
            Button:
                id: converter_btn
                text: 'Convert Miles to Kilometers'
                on_press: app.handle_convert()
            Button:
                id: converter_btn
                text: 'Convert Miles to Kilometers'
                on_press: app.handle_convert()
            Button:
                id: converter_btn
                text: 'Convert Miles to Kilometers'
                on_press: app.handle_convert()
                
        BoxLayout:
            orientation: 'horizontal'
            BoxLayout:
                orientation: 'vertical'
                Label:
                    text: "Test Text"

                    ## Trying to change the background colour of label ##
                    #canvas.before:
                    #    color:
                    #        rgba: 1,1,0,1
                    #    rectangle:
                    #        pos: self.pos
                    #        size: self.size

                Label:
                    text: "Test Text"
                Label:
                    text: "Test Text"
            BoxLayout:
                orientation: 'vertical'
                Label:
                    text: "Test Text"
                Label:
                    text: "Test Text"
                Label:
                    text: "Test Text"
            BoxLayout:
                orientation: 'vertical'
                Label:
                    text: "Test Text"
                Label:
                    text: "Test Text"
                Label:
                    text: "Test Text"
    Label:
        size_hint_y: 0.1
        id: output_label
        text: 'Choose action from the left menu, then select items on the right'

